services:
  - type: web
    name: shieldsight-api
    runtime: python
    rootDirectory: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: HF_REPO_ID
        value: "aashif-dev/shieldsight-models"
    healthCheckPath: /health
    plan: free
